apiVersion: v1
kind: Service 
metadata:
  name: nk-svc
  labels:
    app: myjavaapp 
    version: 2.6.2
spec:
  type: NodePort
  ports:
  - port: 8080
    NodePort: 30001
    protocol: TCP
  selector:
    app: myjavaapp
    version: 2.6.2